server:
  port: 8083

spring:
  application:
    name: forum-message
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: forum-dev
      config:
        server-addr: localhost:8848
        namespace: forum-dev
        file-extension: yaml