server:
  port: 8083

spring:
  application:
    name: forum-message
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: forum-dev
      config:
        namespace: forum-dev
        file-extension: yaml
  config:
    import: nacos:forum-message.yaml