server:
  port: 8081

spring:
  application:
    name: forum-auth
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: forum-dev
      config:
        namespace: forum-dev
        file-extension: yaml
  config:
    import: nacos:forum-auth.yaml
