server:
  port: 8080

spring:
  application:
    name: forum-gateway
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: forum-dev
      config:
        namespace: forum-dev
        file-extension: yaml
  config:
    import: nacos:forum-gateway.yaml
